apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  template:
    spec:
      containers:
      - name: guestbook
        resources:
          requests:
            cpu: "0.1"
            memory: "100MiB"
          limits:
            cpu: "0.1"
            memory: "100Mib"