apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- guestbook-deployment-kustomize.yaml
images:
- name: guestbook
  newName: ghcr.io/isouza-daitan/guestbook
  newTag: v1.6