apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: guestbook
  newName: ghcr.io/isouza-daitan/guestbook
  newTag: 2ea549bca8d0f89097e09d63fefbe5282f42ed31
