apiVersion: batch/v1
kind: Job
metadata:
  name: guestbook-post-deploy-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: test
        image: curlimages/curl
        command: 
          - "curl"
          - "--silent"
          - "--show-error"
          - "--fail-with-body"
          - "http://guestbook:3000/info"
      restartPolicy: Never
  backoffLimit: 2