apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-pr-12
spec:
  destination:
    namespace: guestbook-pr-12
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      images:
        - ghcr.io/isouza-daitan/guestbook:5e014cd2ec93966afd24e6a53fa6987289d723b7
    path: overlays/pr
    repoURL: https://github.com/isouza-daitan/guestbook-go-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
