apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-pr-1099735049
spec:
  destination:
    namespace: guestbook-pr-1099735049
    server: https://kubernetes.default.svc
  project: ""
  source:
    kustomize:
      images:
      - ghcr.io/isouza-daitan/guestbook-go:pr-1099735049
    path: overlays/pr
    repoURL: https://github.com/isouza-daitan/guestbook-go-config
  syncPolicy:
    automated: {}
    syncOptions:
    - Prune=true
    - SelfHeal=true
    - CreateNamespace=true
