apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-pr-3
spec:
  destination:
    namespace: guestbook-pr-3
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      images:
      - ghcr.io/isouza-daitan/guestbook-go:pr-3-1099909628
    path: overlays/pr
    repoURL: https://github.com/isouza-daitan/guestbook-go-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
