apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-pr-13
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: guestbook-pr-13
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/isouza-daitan/guestbook-go-config
    path: overlays/pr
    kustomize:
      images:
        - guestbook-image=ghcr.io/isouza-daitan/guestbook:8793e1a8f2187180218e998782a318e1bcf0e94a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
